server:
  port: 19091 #8083에서 0으로 변경 (랜덤 포트 할당)

spring:
  application:
    name: user-service

jwt:
  secret-key: ${JWT_SECRET:aGVsbG9Xb3JsZFNlY3JldEtleUZvckpXVEF1dGgxMjM0NTY=}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #유레카에 등록될 때 각각의 랜덤 포트 서버들을 구별하기 위한 고유 ID 설정
  instance:
    instance-id: ${spring.application.name}:${spring.instance_id:${random.values}}

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId